--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimpleNPC
build-by-default: true
branches:
- master
- dev
- "2.0"
projects:
  SimpleNPC:
    path: ""
    icon: "/assets/image.png"
    libs:
      - src: brokiem/EasyUI/libEasyUI
        version: 1.0.0
...