--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimpleNPC
branches:
  - master
  - pm4-new
projects:
  SimpleNPC:
    path: ""
    icon: "/assets/icon.png"
    libs:
      - src: brokiem-pm-pl/EasyUI/libEasyUI
        version: 3.0.0
      - src: brokiem-pm-pl/UpdateChecker/UpdateChecker
        version: ^1.0.0
        branch: "pm4"
...