name: SimpleNPC
main: brokiem\snpc\SimpleNPC
version: 2.0.0
api: 3.15.0
author: brokiem

mcpe-protocol: [407, 408, 418, 419, 421, 422, 428, 431]

softdepend: ["Slapper"]
website: https://github.com/brokiem/SimpleNPC/

permissions:
  snpc.spawn:
    default: op
  snpc.edit:
    default: op
  snpc.id:
    default: op
  snpc.notify:
    default: op
  snpc.ui:
    default: op
  snpc.reload:
    default: op
  snpc.remove:
    default: op
  snpc.migrate:
    default: op
  snpc.list:
    default: op
  snpc.rca:
    default: op
